name = "(I Am) All of Me"
author = "lilyb01 & TeamAOF"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9bf8118821849c48bdf3c6bd516c75f4d34dbd3bb4b88936f7e24766e7ff8c13"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
