name = "(I Am) All of Me"
author = "lilyb01 & TeamAOF"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "16e63f52a823ce097839024d401ef2eca783d2e67ad163175ef2da8dc237486b"

[versions]
fabric = "0.16.1"
minecraft = "1.20.1"
