name = "(I Am) All of Me"
author = "lilyb01 & TeamAOF"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a559b3e04cb38e4328ff70be627732c54a31cdd138e2bc60bb9de2314bf0c1d5"

[versions]
fabric = "0.16.1"
minecraft = "1.20.1"
